apiVersion: gs.zzrr.io/v1alpha1
kind: GameService
metadata:
  labels:
    app.kubernetes.io/name: gs-operator
    app.kubernetes.io/managed-by: kustomize
  name: blue-gateway
spec:
  trafficMode: Gateway
  route:
    host: game.example.com
    pathType: Prefix
    pathPrefix: "/connector"
    port: 3010
  gateway:
    parentRef:
      name: shared-gateway
      namespace: gateway-system
      sectionName: http
  extraIngress:
    name: gamelogin
    paths:
      - pathType: Prefix
        path: /serverlogin
        serviceName: logingame-blue
        port: 9020
      - pathType: Prefix
        path: /servergovern
        serviceName: servergovern-blue
        port: 9015
      - pathType: Prefix
        path: /backend
        serviceName: backend-blue
        port: 9010
      - pathType: Prefix
        path: /statsgm
        serviceName: statsgm-blue
        port: 9012
  connectorNamespace: adventure
  podLabelKey: app
  podLabelValue: connector
  deployGroup:
    role: blue
    active: true
  retention:
    enabled: true
    defaultDuration: 24h
